# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Glob of thoughts
email: wuthefwasthat@gmail.com
description: >
  Personal blog of Jeff Wu
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wuthefwasthat.github.io/" # the base hostname & protocol for your site
twitter_username: wuthefwasthat
github_username: wuthefwasthat

# Build settings
markdown: kramdown
